"""Add medication and prescription models

Revision ID: 4cc11c2b2f1a
Revises: d3dc6e9f2600
Create Date: 2025-06-28 23:48:34.592384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc11c2b2f1a'
down_revision = 'd3dc6e9f2600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###